# Cleaning Kaggle Dataset Scraped from Goodreads API
<hr>

The purpose of this notebook is to clean and filter down the Kaggle <strong>"goodreads_books.csv"</strong> so it's ready to be utilized when we extract data from other sources like Amazon.com and Google Books API with the ISBN-13 codes.

The cleaned <strong>"goodreads_books.csv"</strong> will serve as our ETL project foundation.

In [1]:
# Dependencies
import pandas as pd

In [3]:
# Load CSV. This is the dataset where we will get our ISBN-13 codes from.
csv_kaggle = 'Resources/goodreads_books.csv'

goodreads_df = pd.read_csv(csv_kaggle)
goodreads_df.head(5)

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher,Unnamed: 12
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.,NaN
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.,NaN
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic,NaN
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.,NaN
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic,NaN

## Cleaning
<hr>

### Remove bad rows

An extra column in the end was added manually because the dataset was not cleaned to the extent that every row had the same number of columns. There were extra commas (",") in the <strong>"goodreads_books.csv"</strong> file which resulted in some single columns being recognized two columns thus adding unwanted information towards the right of the dataframe.

We decided to resolve this by deleting those rows.

In [4]:
# Fill all the None values as integer 0
goodreads_df = goodreads_df.fillna(0)
goodreads_df.head(2)

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher,Unnamed: 12
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.,0
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.,0

In [5]:
# Filter out bad rows with an extra column of information and drop that column
filt_wanted = goodreads_df.iloc[:,-1] == 0
goodreads_df = goodreads_df.loc[filt_wanted]
goodreads_df = goodreads_df.drop(columns=['Unnamed: 12'])
goodreads_df.head(2)

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.

### Remove duplicated titles

There are books with different ISBN-13 codes yet identical titles, for example, "The Richest Man in Babylon" with the ISBN-13 of  9780451205360 has 194 pages but the other one with the ISBN-13 of 9781419349997 only has 4 pages. This could be an instance where the duplicate is a variation of some sort of the original text. For the purpose of this project, we do not need them thus we will remove those rows.

In [6]:
# Drop rows with duplicated titles
goodreads_df.drop_duplicates(subset='title', keep=False, inplace=True)

In [7]:
# Reset index
goodreads_df.reset_index(drop=True, inplace=True)

In [11]:
# View data
goodreads_df.head(3)

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.
1,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic
2,9,"Unauthorized Harry Potter Book Seven News: ""Ha...",W. Frederick Zimmerman,3.74,0976540606,9780976540601,en-US,152,19,1,4/26/2005,Nimble Books

In [10]:
# Check shape
goodreads_df.shape

(9861, 12)

In [13]:
# Check if there are any other None values
goodreads_df.isna().any()

bookID                False
title                 False
authors               False
average_rating        False
isbn                  False
isbn13                False
language_code         False
  num_pages           False
ratings_count         False
text_reviews_count    False
publication_date      False
publisher             False
dtype: bool

<strong>There is no other None value.</strong>

In [14]:
# Export cleaned csv to folder
goodreads_df.to_csv('Cleaned/goodreads_books_cleaned.csv')